export const enum Identifiers {
	ArgsMissing = 'argsMissing',
	ArgsUnavailable = 'argsUnavailable',
	ArgumentBooleanError = 'booleanError',
	ArgumentFloatError = 'floatError',
	ArgumentFloatTooLarge = 'floatTooLarge',
	ArgumentFloatTooSmall = 'floatTooSmall',
	ArgumentHyperlinkError = 'hyperlinkError',
	ArgumentIntegerError = 'integerError',
	ArgumentIntegerTooLarge = 'integerTooLarge',
	ArgumentIntegerTooSmall = 'integerTooSmall',
	ArgumentNumberError = 'numberError',
	ArgumentNumberTooLarge = 'numberTooLarge',
	ArgumentNumberTooSmall = 'numberTooSmall',
	ArgumentStringTooLong = 'stringTooLong',
	ArgumentStringTooShort = 'stringTooShort',
	ArgumentEnumEmptyError = 'enumEmptyError',
	ArgumentEnumError = 'enumError',
	ArgumentChannelError = 'channelError',
	ArgumentUserError = 'userError',
	ArgumentMemberError = 'memberError',
	ArgumentMessageError = 'messageError'
}
